// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models.sınıflar;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221006090021_deneme2")]
    partial class deneme2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.sınıflar.Turlar", b =>
                {
                    b.Property<int>("turID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bolgesicaklik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurlarturID")
                        .HasColumnType("int");

                    b.Property<string>("bolge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("girisresim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turismi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("turID");

                    b.HasIndex("TurlarturID");

                    b.ToTable("turlars");
                });

            modelBuilder.Entity("WebApplication1.Models.sınıflar.Turlar", b =>
                {
                    b.HasOne("WebApplication1.Models.sınıflar.Turlar", null)
                        .WithMany("turlars")
                        .HasForeignKey("TurlarturID");
                });

            modelBuilder.Entity("WebApplication1.Models.sınıflar.Turlar", b =>
                {
                    b.Navigation("turlars");
                });
#pragma warning restore 612, 618
        }
    }
}
